spring:
  application:
    name: Cinema_Spring_Boot
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      leak-detection-threshold: 2000
    url: jdbc:mysql://db:3306/cinema_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Moscow
    username: cinema_user
    password: cinema_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
  transaction:
    default-timeout: 30
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

    # spring.datasource.url=jdbc:mysql://db:3306/cinema_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Moscow

logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG

application:
  version: 1.0.1

omdb:
  api:
    url: https://www.omdbapi.com/
    key: 35345cc8

management:
  endpoints:
    web:
      exposure:
        include: info,health

security:
  jwt:
    signing:
      key: DJCEJHUGHUDGCHJW632JHEFJHERJ3267JHJHJH732HJCEWD
    expiration: 3600000